
import { 
  House, 
  AirVent, 
  Wrench, 
  Bolt, 
  Bug, 
  Trees,
  Building,
  Construction,
  Brush,
  Sofa,
  Wind,
  Fan,
  Cog,
  FlaskRound,
  Plug,
  Lamp,
  Lightbulb,
  ShowerHead,
  Gauge,
  Heater,
  Paintbrush,
  Camera,
  Bell,
  DoorClosed,
  Sprout,
  TreeDeciduous,
  LucideIcon,
  Scissors,
  Shield,
  Zap,
  Droplets,
  Hammer,
  Eye,
  Leaf,
  Trash2,
  Settings,
  Lock,
  Car,
  Home,
  Briefcase,
  Smartphone,
  Wifi,
  Monitor,
  Router,
  Server
} from 'lucide-react';

interface ServiceIconProps {
  iconName: string;
  className?: string;
  size?: number;
}

const iconMap: Record<string, LucideIcon> = {
  house: House,
  'air-vent': AirVent,
  wrench: Wrench,
  bolt: Bolt,
  bug: Bug,
  trees: Trees,
  building: Building,
  construction: Construction,
  brush: Brush,
  sofa: Sofa,
  wind: Wind,
  fan: Fan,
  cog: Cog,
  'flask-round': FlaskRound,
  plug: Plug,
  lamp: Lamp,
  lightbulb: Lightbulb,
  'shower-head': ShowerHead,
  gauge: Gauge,
  heater: Heater,
  paintbrush: Paintbrush,
  camera: Camera,
  bell: Bell,
  'door-closed': DoorClosed,
  sprout: Sprout,
  'tree-deciduous': TreeDeciduous,
  scissors: Scissors,
  shield: Shield,
  zap: Zap,
  droplets: Droplets,
  hammer: Hammer,
  eye: Eye,
  leaf: Leaf,
  'trash-2': Trash2,
  settings: Settings,
  lock: Lock,
  car: Car,
  home: Home,
  briefcase: Briefcase,
  smartphone: Smartphone,
  wifi: Wifi,
  monitor: Monitor,
  router: Router,
  server: Server,
  // Add plumbing-specific icon
  plumbing: Wrench,
  electrical: Bolt,
  'ac-repair': AirVent,
  cleaning: Brush,
  painting: Paintbrush,
  carpentry: Hammer,
  security: Shield,
  networking: Wifi,
};

export default function ServiceIcon({ iconName, className = "", size = 24 }: ServiceIconProps) {
  const Icon = iconMap[iconName] || House;
  
  return <Icon size={size} className={className} />;
}
